CREATE SCHEMA ELPROMEDIADOR;

USE ELPROMEDIADOR;

CREATE TABLE CONSULTA (
    CODIGO_UPC VARCHAR(15), -- CODIGO UPC
    FECHA_HORA_INICIO DATETIME, -- FECHA Y HORA INICIO DE LA CONSULTA
    FECHA_HORA_FIN DATETIME, -- FECHA Y HORA FIN DE LA CONSULTA
    IP VARCHAR(20), -- IP DEL VISITANTE
    RESULTADO TINYINT(1), -- RESULTADO DEL LOGIN UPC (1/0)
    NOMBRE VARCHAR(400), -- NOMBRE DEL ALUMNO (RESULTADO = 1)
    CARRERA VARCHAR(400), -- CARRERA DEL ALUMNO (RESULTADO = 1)
    OBS VARCHAR(1000) -- OBSERVACIONES O ERRORES (SEA EL CASO)
);
